### ISSUE TITLE
Can't build Revit2017 from source.

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoRevit#1434]
I made an update from 1.2 to 1.2.1 and I am having trouble building the repo. My steps were as follows. Build Dynamo 1.2.1_master (no issues here) then try building the Dynamo.Revit from Revit2017 branch and it fails with unresolved references. Here's the console output: 

1>------ Rebuild All started: Project: AssemblyInfoGenerator, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: DynamoRevitIcons, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: DynamoAddinGenerator, Configuration: Debug Any CPU ------
3>  DynamoAddinGenerator -> C:\Users\ksobon\Google Drive\Work\Dynamo\bin\AnyCPU\Debug\DynamoAddInGenerator.exe
2>  DynamoRevitIcons -> C:\Users\ksobon\Google Drive\Work\Dynamo\bin\AnyCPU\Debug\Revit_2017\DynamoRevitIcons.dll
1>  'C:\Users\ksobon\Google' is not recognized as an internal or external command,
1>  operable program or batch file.
1>C:\Users\ksobon\Google Drive\Work\DynamoRevit\src\AssemblySharedInfoGenerator\AssemblyInfoGenerator.csproj(78,5): warning MSB3073: The command "C:\Users\ksobon\Google Drive\Work\DynamoRevit\src\restorepackages.bat" exited with code 9009.

**Comment by mjkkirschner** [comment]
@sharadkjaiswal 
```
Drive\Work\DynamoRevit\src\AssemblySharedInfoGenerator\AssemblyInfoGenerator.csproj(78,5): warning MSB3073: The command "C:\Users\ksobon\Google Drive\Work\DynamoRevit\src\restorepackages.bat" exited with code 9009.
```

**Comment by sharadkjaiswal** [comment]
@ksobon are you using windows 10? Can you please run the `C:\Users\ksobon\Google Drive\Work\DynamoRevit\src\restorepackages.bat` file with admin privilege before starting your build?

**Comment by sharadkjaiswal** [comment]
It seems space in the folder name `Google Drive` is creating the issue. @ellensi please look into it.

**Comment by ellensi** [comment]
This build issue should have been fixed.

**Comment by ksobon** [comment]
it still can't get it to build....

![image](https://cloud.githubusercontent.com/assets/529781/21732231/8b289196-d426-11e6-8b15-abcd1588af14.png)
