### ISSUE TITLE
Units in Text Size

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#1576]
## Dynamo version

1.2.3.502

## Revit version

2017.2

## Operating system

Windows 10x64

## What did you do? 

Get Parameter Name (Text Size) from TextElementType

## What did you expect to see?

Display Units (5mm)

## What did you see instead?

Feet Units

![2017-02-22_11-03-31](https://cloud.githubusercontent.com/assets/4299930/23206815/5e977528-f8ef-11e6-9426-35651fba6089.png)

**Comment by eibre** [comment]
This was fixed here: https://github.com/DynamoDS/DynamoRevit/pull/1493

Let's hope it finds its way into the daylies soon...

**Comment by ksobon** [comment]
can you close the issue?

**Comment by ParametricMonkey** [comment]
Where has this been fixed? I'm using the latest stable release - 1.3.2.2480 and the problem is still there. @kronz

**Comment by QilongTang** [comment]
@ParametricMonkey It's fixed in next release 1.3.3 and daily builds as well

**Comment by ParametricMonkey** [comment]
when will 1.3.3 be released? I though the next version was 2.0??

**Comment by QilongTang** [comment]
@ParametricMonkey RC1.3.3 will be released with Revit 2019, RC2.0 will be released with Revit 2019.1. At the same time, daily builds for pre 2.0 are there available already.
