### ISSUE TITLE
Group styles multiplying shamelessly in 2.16

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#2881]
## Dynamo version

DynamoRevit 2.16.1.6510
DynamoCore 2.16.1.2727

## Revit version

2023.1 (23.1.1.24)

## Operating system

Windows 10

## What did you do? 

1. Created a custom group style:
![grafik](https://user-images.githubusercontent.com/3014437/203996326-375686c3-f2cd-482e-90e9-7d4fb75489de.png)
2. Closed Dynamo
3. Opened and closed Dynamo a couple of times
4. Opened the settings panel and found my group styles had multiplied like Tribbles:
![grafik](https://user-images.githubusercontent.com/3014437/203997734-fe4bc3f5-b74f-497d-b00c-d7939e8ced2b.png)

## What did you expect to see?

The DynamoSettings.xml file not cluttering up with multiple custom colors

## What did you see instead?

![grafik](https://user-images.githubusercontent.com/3014437/203998079-8d324608-03fa-499c-b8dc-6daf6b7b208a.png)

I originally discovered this behavior while I was preparing the DynamoSettings.xml for our software deployment. I had added our company group styles in the ```GroupStyleItemsList``` section and it worked perfectly the first time I started Dynamo. After a couple more launches within the same Revit session I noticed there now were a whole lot more of the custom group styles. 
Perhaps a serialization/deserialization issue?

**Comment by QilongTang** [comment]
> @QilongTang I believe this bug is fixed in 2.17, correct?

I believe so, we added Guids for group styles so comparison will be more accurate

**Comment by Amoursol** [comment]
@andydandy74 this should be fixed when Revit 2024 comes out, or available to test today in Sandbox.

**Comment by fadelm0** [comment]
This is still an issue on Dynamo version 2.19.3 on Revit 2024.

Steps to reproduce:

1. Create a new group style
2. Close dynamo
3. Open dynamo
4. Check the group styles where a clone now appears

This can be repeated many times with the same result.

A full restart of Revit "fixes" it again and resets the group styles back to their normal values.

**Comment by QilongTang** [comment]
hi @fadelm0 I cant reproduce this in 2.19.3 sandbox or latest 3.2.0 sandbox. @avidit @Mikhinja Are you aware of such issue in Revit 2024?
